### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by Remonell** [halloverden/symfony-doctrine-sql-logger-bundle#3]
All I did was running your composer require command:
![Screenshot_2](https://user-images.githubusercontent.com/8575168/114682120-16f29900-9d0f-11eb-8b9b-8f20fbd5fd86.png)

**Comment by erichjsonfosse** [comment]
@Remonell Could you provide us with the verbose output of the `cache:clear` command?

**Comment by Remonell** [comment]
@erichjsonfosse Sure. I ran the cache:clear command after I reverted the install attempt of your bundle. 
![Screenshot_3](https://user-images.githubusercontent.com/8575168/114686300-f0366180-9d12-11eb-9337-dd037515e122.png)

**Comment by tomme87** [comment]
@Remonell Thank you for your report. issue is identified. Will update the package asap.

as temporary workaround you can add this to your service definitions:
```yaml
HalloVerden\DoctrineSqlLoggerBundle\Loggers\QueryExecutionTimeLogger:
    arguments:
        $executionTimeLogger: '@logger'
```
